name: Expresiones
run-name: Â¡Estoy aprendiendo a usar Expresiones!

on:
  workflow_dispatch:
    inputs:
      edad:
        description: 'Edad'
        required: true
        type: integer
      nombre:
        description: 'Tu nombre'
        required: true
        default: 'Juan'
        type: string

jobs:

  mayor:
    if: ${{ inputs.edad >= 18 }}
    runs-on: ubuntu-latest
    steps:
      - name: Mensaje mayor de edad
        run: echo "${{ inputs.nombre }} es mayor de edad"

  menor:
    if: ${{ inputs.edad < 18 }}
    runs-on: ubuntu-latest
    steps:
      - name: Mensaje menor de edad
        run: echo "${{ inputs.nombre }} es menor de edad"
