name: Saludo usando variables y secretos

on:
  workflow_dispatch:  # Permite ejecutarlo manualmente

# Variables globales
env:
  DIA_DE_SEMANA: Lunes

jobs:

  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola        # Variable local SOLO para este job
    steps:
      - name: Saludo usando variables
        run: echo "$SALUDO, ${{ vars.NOMBRE }}. Hoy es ${{ env.DIA_DE_SEMANA }}!"

  saludo-secretos:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola        # Debes redefinirla aquí si quieres usarla
    steps:
      - name: Saludo usando secretos
        run: echo "$SALUDO, ${{ vars.NOMBRE }}. Tu contraseña es ${{ secrets.CONTRASENA }}!"
